#
# Makefile for Real Time Clock driver for SD2068
#
# Copyright (C) 2017 OpenWrt.org
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version
# 2 of the License, or (at your option) any later version.
#

obj-${CONFIG_RTC_SD2068} := rtc-sd2068.o
